import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import MainPage from './main';

const Home = () => {
  const [, setData] = useState();
  useEffect(() => {
    axios.get('https://reqres.in/api/unknown').then((res) => setData(res.data.data));
  }, []);

  return (
    <>
      <Head>
        <title>E-AggieMall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainPage />
    </>
  );
};

export default Home;
